# Generated by Django 2.2 on 2020-08-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0002_poet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poet',
            name='user_name',
        ),
        migrations.AddField(
            model_name='poet',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poets', to='app_level.User'),
            preserve_default=False,
        ),
    ]
