# Generated by Django 2.2 on 2020-08-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0004_auto_20200819_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='full_name',
        ),
    ]
