# Generated by Django 2.2 on 2020-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0005_auto_20200819_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='quotes_liked', to='app_level.User'),
        ),
    ]
