# Generated by Django 3.1.1 on 2020-10-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default='zip', max_length=15),
            preserve_default=False,
        ),
    ]
