# Generated by Django 2.2 on 2020-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
